'use client'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { LayoutDashboard, ListChecks, Store, FlaskConical, Upload, MessageCircle, Menu, LogOut, ChevronDown, Brain, ArrowLeftRight, BookOpen } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '@/lib/auth'
const nav = [{ href:'/dashboard', label:'Tableau de bord', icon:LayoutDashboard }, { href:'/recommendations', label:'Recommandations', icon:ListChecks }, { href:'/shops', label:'Boutiques', icon:Store }, { href:'/simulation', label:'Simulation', icon:FlaskConical }, { href:'/redistribution', label:'Redistribution', icon:ArrowLeftRight }, { href:'/models', label:'Modèles', icon:Brain }, { href:'/glossaire', label:'Glossaire', icon:BookOpen }, { href:'/import', label:'Import dispatching', icon:Upload }, { href:'/assistant', label:'Assistant IA', icon:MessageCircle }]
const titles: Record<string,string> = { '/dashboard':'Tableau de bord', '/recommendations':'Recommandations', '/shops':'Boutiques', '/simulation':'Simulation', '/redistribution':'Redistribution', '/models':'Modèles', '/glossaire':'Glossaire', '/import':'Import dispatching', '/assistant':'Assistant IA' }
export function DashboardShell({ children }: { children: React.ReactNode }) { const path=usePathname(); const router=useRouter(); const { user, logout }=useAuth(); const [open,setOpen]=useState(false); if(path==='/login') return <>{children}</>; const title=path.startsWith('/shops/')?'Détail boutique':titles[path]||'Tableau de bord'; return <div className="min-h-screen bg-[#f6f6f6] text-[#171717]"><aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col bg-[#050505] px-5 py-6 text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="mb-10 flex items-center gap-3"><span className="size-3 rounded-full bg-[#ff7900]"/><div><div className="text-sm font-bold tracking-tight">Dispatching</div><div className="text-xs text-white/60">Intelligent</div></div></div><nav className="flex flex-1 flex-col gap-2">{nav.map(({href,label,icon:Icon})=>{const active=path===href||(href==='/shops'&&path.startsWith('/shops'));return <Link key={href} href={href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition-colors ${active?'bg-[#ff7900] font-semibold text-white':'text-white/65 hover:bg-white/10 hover:text-white'}`}><Icon className="size-4"/> {label}</Link>})}</nav><div className="border-t border-white/10 pt-4 text-xs text-white/40">Orange Tunisie · v1.0</div></aside>{open&&<button aria-label="Fermer le menu" className="fixed inset-0 z-30 bg-black/40 lg:hidden" onClick={()=>setOpen(false)}/>}<div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-black/5 bg-white/90 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-black/5 lg:hidden" onClick={()=>setOpen(true)} aria-label="Ouvrir le menu"><Menu className="size-5"/></button><div><h1 className="text-lg font-bold tracking-tight">{title}</h1><p className="hidden text-xs text-black/45 sm:block">Opérations retail · Orange Tunisie</p></div></div><div className="relative flex items-center gap-3"><span className="hidden max-w-48 truncate text-xs text-black/50 md:block">{user?.email}</span><button aria-label="Menu du compte" onClick={()=>setOpen(!open)} className="flex size-9 items-center justify-center gap-1 rounded-full bg-[#ff7900] text-xs font-bold text-white">OT</button>{open&&<div className="absolute right-0 top-12 w-56 rounded-xl border bg-white p-2 shadow-xl"><p className="truncate px-3 py-2 text-xs text-black/55">{user?.email}</p><button onClick={()=>{logout();router.push('/login')}} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-black/5"><LogOut className="size-4"/> Se déconnecter</button></div>}</div></header><main className="p-5 md:p-8">{children}</main></div></div> }
