'use client'

import { useEffect, useState } from 'react'
import { ArrowRight, Info } from 'lucide-react'
import { extraApi, extraFormat, type Divergence, type TransferDiagnostic, type Transfer } from '@/lib/api-extra'

const severityLevel: Record<string, number> = { RUPTURE: 100, CRITIQUE: 85, URGENT: 60, SURVEILLANCE: 35, NORMAL: 10 }
const severityColor: Record<string, string> = { RUPTURE: '#dc2626', CRITIQUE: '#ef4444', URGENT: '#ff7900', SURVEILLANCE: '#f59e0b', NORMAL: '#10b981' }

function Verdict({ diagnostic }: { diagnostic: TransferDiagnostic }) {
  const tone = diagnostic.verdict === 'aucun recouvrement' ? ['bg-amber-50', 'border-amber-200', 'text-amber-700'] : diagnostic.verdict === 'recouvrement sans transfert' ? ['bg-blue-50', 'border-blue-200', 'text-blue-700'] : ['bg-emerald-50', 'border-emerald-200', 'text-emerald-700']
  return <><section className={`rounded-2xl border p-5 ${tone[0]} ${tone[1]}`}><div className="flex gap-3"><Info className={`size-5 shrink-0 ${tone[2]}`}/><div><h3 className="font-bold capitalize">{diagnostic.verdict}</h3><p className="mt-2 text-sm leading-relaxed">{diagnostic.explication}</p></div></div></section><div className="grid grid-cols-3 gap-4">{[['Situations en manque', diagnostic.total_besoins], ['Situations en excédent', diagnostic.total_sources], ['Transferts théoriquement possibles', diagnostic.appariements_theoriques]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-black/5 bg-white p-4"><b className="block text-2xl">{extraFormat(Number(value))}</b><p className="mt-1 text-xs text-black/45">{label}</p></div>)}</div></>
}

export function RedistributionView() { const [diagnostic, setDiagnostic] = useState<TransferDiagnostic | null>(null); const [transfers, setTransfers] = useState<Transfer[]>([]); const [divergences, setDivergences] = useState<Divergence[]>([]); useEffect(() => { Promise.all([extraApi.diagnostic(), extraApi.transfers(), extraApi.divergence()]).then(([d, t, v]) => { setDiagnostic(d); setTransfers(t); setDivergences(v) }).catch(() => {}) }, []); if (!diagnostic) return <main className="mx-auto max-w-6xl"><div className="h-40 animate-pulse rounded-2xl bg-black/5"/></main>
  const max = Math.max(1, ...diagnostic.matrice.flatMap(x => [x.besoins, x.sources])); const terrainAlarme = divergences.filter(d => d.lecture === 'terrain alarme, modele calme'); const modeleAlarme = divergences.filter(d => d.lecture === 'modele alarme, terrain calme')
  return <main className="mx-auto max-w-6xl space-y-6"><div><h2 className="text-3xl font-bold tracking-tight">Redistribution</h2><p className="mt-2 text-sm text-black/45">Quand le réseau peut-il se rééquilibrer ?</p></div><Verdict diagnostic={diagnostic}/><section className="rounded-2xl border border-black/5 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-bold">Besoins et sources par produit</h3><p className="mt-1 text-sm text-black/50">Un transfert n&apos;est possible que si un produit présente des barres des deux côtés.</p></div><div className="flex gap-4 text-xs"><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-red-500"/>Boutiques en manque</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-blue-500"/>Boutiques en excédent</span></div></div><div className="mt-6 flex flex-col gap-4">{diagnostic.matrice.map(row => <div key={row.product_id} title={`${row.product_id} — ${row.besoins} boutiques en manque, ${row.sources} en excédent, ${row.appariements_possibles ? 'transfert possible' : 'aucun transfert possible'}`}><div className="mb-1 flex justify-between text-xs"><span className="font-medium">{row.product_id}</span><span className="text-black/45">{row.besoins} / {row.sources}</span></div><div className="flex h-2 gap-1"><div className="rounded-full bg-red-500" style={{ width: `${row.besoins / max * 100}%` }}/><div className="rounded-full bg-blue-500" style={{ width: `${row.sources / max * 100}%` }}/></div></div>)}</div></section><section className="grid gap-5 lg:grid-cols-2"><DivergenceColumn title="Terrain en alarme, modèle calme" subtitle="Le terrain signale une tension que le modèle ne prévoit pas." rows={terrainAlarme}/><DivergenceColumn title="Modèle en alarme, terrain calme" subtitle="Le modèle anticipe une tension encore invisible sur le terrain." rows={modeleAlarme}/></section><section className="rounded-2xl border border-black/5 bg-white p-5"><h3 className="font-bold">Plan de transfert</h3>{transfers.length ? <div className="mt-4 flex flex-col gap-3">{transfers.map(t => <div key={`${t.source_shop_id}-${t.target_shop_id}-${t.product_id}`} className="flex flex-wrap items-center gap-3 rounded-xl bg-[#fafafa] p-3 text-xs"><b>{t.source_shop_id}</b><ArrowRight className="size-4"/><b>{t.target_shop_id}</b><span className="text-black/45">{t.product_id} · {t.quantity} unités</span></div>)}</div> : <p className="mt-3 text-sm text-black/45">Aucun transfert proposé.</p>}</section></main>
}

function DivergenceColumn({ title, subtitle, rows }: { title: string; subtitle: string; rows: Divergence[] }) { return <div className="rounded-2xl border border-black/5 bg-white p-5"><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs leading-relaxed text-black/45">{subtitle}</p><div className="mt-4 flex flex-col gap-3">{rows.length ? rows.map(row => { const now = row.severity_now.toUpperCase(); const level = severityLevel[now] ?? 10; const color = severityColor[now] ?? '#10b981'; return <div key={`${row.shop_id}-${row.product_id}`} className="rounded-xl bg-[#fafafa] p-3 text-xs"><b>{row.shop_id}</b><span className="ml-2 text-black/45">{row.governorate}</span><p className="mt-1">{row.product_id}</p><div className="mt-3 flex flex-col gap-2"><div><div className="mb-1 flex justify-between"><span>Terrain aujourd&apos;hui</span><b style={{ color }}>{now}</b></div><div className="h-2 rounded-full bg-black/5"><div className="h-2 rounded-full" style={{ width: `${level}%`, background: color }}/></div></div><div><div className="mb-1 flex justify-between"><span>Modèle à 7 jours</span><b>{extraFormat(row.proba_stockout_7d * 100)} %</b></div><div className="h-2 rounded-full bg-black/5"><div className="h-2 rounded-full bg-[#171717]" style={{ width: `${Math.max(0, Math.min(100, row.proba_stockout_7d * 100))}%` }}/></div></div></div><p className="mt-3 text-xs text-black/45">stock {extraFormat(row.stock_on_hand)} · couverture {extraFormat(row.coverage_days_now, 1)} j · demande prévue {extraFormat(row.predicted_demand_7d, 1)} sur 7 jours</p></div> }) : <p className="min-h-20 py-6 text-center text-sm text-black/40">Aucun désaccord de ce type actuellement</p>}</div></div> }
