import { DASHBOARD_API, formatNumber } from './api'
export type RiskSummary = { reference_date: string; shops_total: number; critique: number; eleve: number; modere: number; faible: number; demand_7d_total: number; demand_7d_at_risk: number; share_of_demand_at_risk: number; units_requested: number; units_allocated: number; units_unserved: number; national_coverage_of_need: number; shops_non_servi: number; shops_peu_servi: number; shops_partiel: number; shops_servi: number }
export type RiskShop = { shop_id: string; shop_name: string; shop_type: string; governorate: string; region: string; latitude: number; longitude: number; lead_time_days: number; urgency_score: number; risk_level: string; products_total: number; products_at_risk: number; products_out_of_stock: number; demand_7d_total: number; demand_7d_at_risk: number; max_stockout_proba: number; units_requested: number; units_allocated: number; coverage_of_need: number; units_unserved: number; unserved_share: number; action_level: string }
export type RiskPoint = { shop_id: string; shop_name: string; governorate: string; region: string; latitude: number; longitude: number; score: number; level: string; urgency_score: number; risk_level: string; unserved_share: number; action_level: string; products_at_risk: number; products_total: number; units_requested: number; units_allocated: number; units_unserved: number }
export type RiskMap = { scale: string; score_meaning: string; shops_without_coordinates: number; thresholds: Record<string, number>; points: RiskPoint[] }
export type HeatCell = { governorate: string; product_id: string; shops: number; shops_at_risk: number; share_at_risk: number; mean_stockout_proba: number }
export type RegionRisk = { region: string; shops: number; shops_critique: number; shops_eleve: number; demand_7d_total: number; demand_7d_at_risk: number; units_requested: number; units_allocated: number; units_unserved: number; shops_non_servi: number; share_of_demand_at_risk: number; coverage_of_need: number }
async function request<T>(path: string) { const response = await fetch(`${DASHBOARD_API}${path}`); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || `Erreur API (${response.status})`); return body as T }
export const riskApi = { summary: () => request<RiskSummary>('/risk/summary'), shops: (sort = 'deficit') => request<RiskShop[]>(`/risk/shops?unserved_only=true&sort_by=${sort}&limit=50`), map: (scale: 'unserved'|'risk') => request<RiskMap>(`/risk/map?scale=${scale}`), heatmap: () => request<HeatCell[]>('/risk/heatmap'), regions: () => request<RegionRisk[]>('/risk/by_region') }
export { formatNumber }
