import { DASHBOARD_API, formatDate, formatNumber } from './api'

export type AllocationKpis = { recommendation_date: string; run_at: string; policy: string; coverage_days_param: number; depot_available: number; total_requested: number; total_allocated: number; depot_service_rate: number; shops_fully_served: number; shops_partially_served: number; shops_deferred: number; stockouts_resolved: number; withdrawal_lines: number }
export type AllocationProduct = { product_id: string; depot_available: number; total_requested: number; total_allocated: number; n_servi: number; n_partiel: number; n_reporte: number; n_ruptures_resolues: number; service_rate: number }
export type AllocationLine = { shop_id: string; product_id: string; recommendation_type: string; priority: string; allocation_severity: string; suggested_qty: number; qty_allocated: number; allocation_status: string; allocation_reason: string; current_stock: number; stock_in_transit: number; estimated_7d_demand: number; stockout_risk_score: number }
export type DepotStock = { product_id: string; qty_available: number; daily_demand_nat: number; coverage_days_param: number; source: string; generated_at: string }
export type AllocationHistory = Omit<AllocationKpis, 'recommendation_date' | 'run_at' | 'depot_available' | 'total_requested' | 'total_allocated' | 'shops_partially_served' | 'withdrawal_lines'> & { run_at: string; recommendation_date: string; depot_available: number; total_requested: number; total_allocated: number; shops_partially_served?: number }

async function request<T>(path: string, init?: RequestInit) { const response = await fetch(`${DASHBOARD_API}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || `Erreur API (${response.status})`); return body as T }
export const allocationApi = { kpis: () => request<AllocationKpis>('/allocation/kpis'), products: () => request<AllocationProduct[]>('/allocation/by_product'), lines: (params: Record<string,string>) => { const query = new URLSearchParams(Object.entries(params).filter(([, value]) => value)); query.set('limit', '5000'); return request<AllocationLine[]>(`/allocation/lines?${query}`) }, stock: () => request<DepotStock[]>('/allocation/depot_stock'), history: () => request<AllocationHistory[]>('/allocation/history?limit=20'), run: () => request<{ job_type: string; status: string; duration_seconds: number; output: string }>(`${process.env.NEXT_PUBLIC_JOBS_API_URL || 'http://localhost:8005'}/run/allocation`, { method: 'POST' }) }
export { formatDate, formatNumber }
