'use client'
import { useCallback, useEffect, useState } from 'react'
import { OrderKpiCards } from '@/components/ordres/order-kpi-cards'
import { OrderTable } from '@/components/ordres/order-table'
import { OrderConfigPanel } from '@/components/ordres/order-config-panel'
import { OrderBlockedChart } from '@/components/ordres/order-blocked-chart'
import { DepotStockTable } from '@/components/ordres/depot-stock-table'
import { ordersApi, type Order, type OrderConfig, type OrderKpis, type OrderStatus, type BlockedReason, type DepotStock, type GenerateSummary } from '@/lib/api-orders'
const tabs:[string,OrderStatus|undefined][]=[['En attente','PROPOSE'],['Validés','VALIDE'],['Émis','EMIS'],['Reçus','RECU'],['Annulés','ANNULE'],['Tous',undefined]]
export default function OrdresPage(){const [kpis,setKpis]=useState<OrderKpis|null>(null),[orders,setOrders]=useState<Order[]>([]),[config,setConfig]=useState<OrderConfig|null>(null),[blocked,setBlocked]=useState<BlockedReason[]>([]),[stock,setStock]=useState<DepotStock|null>(null),[status,setStatus]=useState<OrderStatus|undefined>('PROPOSE'),[auto,setAuto]=useState(false),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[decision,setDecision]=useState('')
const load=useCallback(async()=>{setLoading(true);setError(null);try{const [a,b,c,d,e]=await Promise.all([ordersApi.kpis(),ordersApi.list({status,auto_only:auto,limit:2000}),ordersApi.config(),ordersApi.blocked(),ordersApi.depotStock()]);setKpis(a);setOrders(b);setConfig(c);setBlocked(d);setStock(e)}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les ordres.')}finally{setLoading(false)}},[status,auto]);useEffect(()=>{void load()},[load]);
const act=async(o:Order,a:'validate'|'emit'|'receive'|'cancel')=>{const name=window.prompt('Votre nom');if(!name)return;if(a==='cancel'&&!window.prompt('Motif'))return;try{await ordersApi.action(o.order_id,a,name);setNotice('Décision enregistrée.');await load()}catch(e){setNotice(e instanceof Error?e.message:'La décision a échoué.')}}
const generate=async()=>{try{const s:GenerateSummary=await ordersApi.generate();setNotice(s.message||`${s.crees} créés, ${s.auto_emis} émis automatiquement, ${s.unites_sorties_du_depot??0} unités sorties du dépôt.`);await load()}catch(e){setNotice(e instanceof Error?e.message:'La génération a échoué.')}}
return <main className="mx-auto flex max-w-7xl flex-col gap-6 p-5 md:p-8"><div><p className="mb-2 text-xs font-bold uppercase tracking-widest text-[#ff7900]">Dispatching intelligent</p><h2 className="text-3xl font-bold tracking-tight">Ordres de réassort</h2><p className="mt-2 text-sm text-black/50">L&apos;allocation décide quoi expédier ; cette page suit ce qui est réellement commandé, de la proposition à la réception.</p></div>{notice&&<div role="status" className="flex justify-between rounded-xl border border-orange-200 bg-orange-50 p-3 text-sm">{notice}<button onClick={()=>setNotice(null)}>×</button></div>}{error&&<div role="alert" className="flex justify-between rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}<button onClick={()=>void load()} className="font-semibold underline">Réessayer</button></div>}{loading&&!kpis&&<p className="text-sm text-black/50">Chargement des ordres…</p>}{kpis&&<OrderKpiCards data={kpis}/>}<div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><button onClick={()=>void generate()} className="rounded-lg bg-[#ff7900] px-4 py-2 font-semibold text-white">Générer les ordres</button><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg bg-black/5 p-1">{tabs.map(([label,value])=><button key={label} onClick={()=>{setStatus(value);setPage(1)}} className={`rounded-md px-3 py-2 text-xs ${status===value?'bg-white font-semibold shadow-sm':''}`}>{label}</button>)}</div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);setPage(1)}} className="accent-[#ff7900]"/>Émis automatiquement uniquement</label></div></div>{!loading&&<><OrderTable orders={orders.slice((page-1)*25,page*25)} onAction={(o,a)=>void act(o,a)}/>{orders.length>25&&<div className="flex justify-center gap-3 text-sm"><button disabled={page===1} onClick={()=>setPage(page-1)} className="rounded border px-3 py-1 disabled:opacity-40">Précédent</button><span className="py-1">Page {page} / {Math.ceil(orders.length/25)}</span><button disabled={page>=Math.ceil(orders.length/25)} onClick={()=>setPage(page+1)} className="rounded border px-3 py-1 disabled:opacity-40">Suivante</button></div>}</>}{config&&<OrderConfigPanel config={config} onSave={async(v)=>{try{const next=await ordersApi.updateConfig({...v,updated_by:decision||'dashboard'});setConfig(next);setNotice('Configuration enregistrée.')}catch(e){setNotice(e instanceof Error?e.message:'Configuration impossible à enregistrer.')}}}/>}<label className="text-sm">Nom de décisionnaire pour la configuration<input value={decision} onChange={e=>setDecision(e.target.value)} placeholder="Votre nom" className="ml-2 rounded border px-2 py-1"/></label><div className="grid gap-6 lg:grid-cols-2">{<OrderBlockedChart data={blocked}/>} {stock&&<DepotStockTable data={stock}/>}</div></main>}
